// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Task_Reminder.Api.Data;

#nullable disable

namespace Task_Reminder.Api.Migrations
{
    [DbContext(typeof(TaskReminderDbContext))]
    [Migration("20260312234852_OfficeWorkflowExpansion")]
    partial class OfficeWorkflowExpansion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.RecurringTaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("EndDateLocal")
                        .HasColumnType("date");

                    b.Property<int?>("EscalateAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EscalateToUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PatientReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("integer");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReminderRepeatMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<DateOnly>("StartDateLocal")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("TimeOfDayLocal")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EscalateToUserId");

                    b.HasIndex("IsActive");

                    b.ToTable("recurring_task_definitions", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("task_history", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EscalateAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EscalateToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EscalatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("GeneratedForDateLocal")
                        .HasColumnType("date");

                    b.Property<Guid?>("GeneratedFromRecurringTaskDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PatientReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReminderRepeatMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<DateTime?>("SnoozeUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DueAtUtc");

                    b.HasIndex("EscalateToUserId");

                    b.HasIndex("Status");

                    b.HasIndex("GeneratedFromRecurringTaskDefinitionId", "GeneratedForDateLocal")
                        .IsUnique();

                    b.ToTable("task_items", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.UserNotificationPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EnableSoundForUrgentReminders")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveAssignedTaskReminders")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveOverdueEscalationAlerts")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveRecurringTaskGenerationAlerts")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveUnassignedTaskReminders")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("user_notification_preferences", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.RecurringTaskDefinition", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "AssignedUser")
                        .WithMany("AssignedRecurringTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedRecurringTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "EscalateToUser")
                        .WithMany("EscalatedRecurringTasks")
                        .HasForeignKey("EscalateToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("EscalateToUser");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskHistory", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "PerformedByUser")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "ClaimedByUser")
                        .WithMany("ClaimedTasks")
                        .HasForeignKey("ClaimedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "EscalateToUser")
                        .WithMany("EscalatedTasks")
                        .HasForeignKey("EscalateToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.RecurringTaskDefinition", "GeneratedFromRecurringTaskDefinition")
                        .WithMany("GeneratedTasks")
                        .HasForeignKey("GeneratedFromRecurringTaskDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");

                    b.Navigation("ClaimedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("EscalateToUser");

                    b.Navigation("GeneratedFromRecurringTaskDefinition");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.UserNotificationPreference", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "User")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("Task_Reminder.Api.Domain.Entities.UserNotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.RecurringTaskDefinition", b =>
                {
                    b.Navigation("GeneratedTasks");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("HistoryEntries");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedRecurringTasks");

                    b.Navigation("AssignedTasks");

                    b.Navigation("ClaimedTasks");

                    b.Navigation("CreatedRecurringTasks");

                    b.Navigation("CreatedTasks");

                    b.Navigation("EscalatedRecurringTasks");

                    b.Navigation("EscalatedTasks");

                    b.Navigation("HistoryEntries");

                    b.Navigation("NotificationPreference");
                });
#pragma warning restore 612, 618
        }
    }
}
