// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Task_Reminder.Api.Data;

#nullable disable

namespace Task_Reminder.Api.Migrations
{
    [DbContext(typeof(TaskReminderDbContext))]
    partial class TaskReminderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.AppointmentWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AppointmentDateLocal")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("AppointmentTimeLocal")
                        .HasColumnType("interval");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BalanceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConfirmationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsuranceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PatientReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDateLocal");

                    b.HasIndex("SourceSystem", "SourceReference")
                        .IsUnique();

                    b.ToTable("appointment_work_items", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedByDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedAtUtc");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("EntityType", "PerformedAtUtc");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.BalanceFollowUpWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("AppointmentWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DueReasonNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("FollowUpDateLocal")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PatientReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentWorkItemId");

                    b.HasIndex("FollowUpDateLocal");

                    b.ToTable("balance_follow_up_work_items", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.ContactLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BalanceFollowUpWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("InsuranceWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentWorkItemId");

                    b.HasIndex("BalanceFollowUpWorkItemId");

                    b.HasIndex("InsuranceWorkItemId");

                    b.HasIndex("PerformedAtUtc");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("contact_logs", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.ExternalIntegrationProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderType")
                        .IsUnique();

                    b.ToTable("external_integration_provider_configs", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.ExternalIntegrationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ProviderConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderConfigId", "StartedAtUtc");

                    b.ToTable("external_integration_runs", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.InsuranceWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AnnualMaximum")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("AppointmentDateLocal")
                        .HasColumnType("date");

                    b.Property<Guid?>("AppointmentWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("CopayAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DeductibleAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("EligibilityStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FrequencyNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GroupNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IssueType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MemberId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MissingInfoNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PatientReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlanName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("RemainingMaximum")
                        .HasColumnType("numeric");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VerificationCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("VerificationRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WaitingPeriodNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDateLocal");

                    b.HasIndex("AppointmentWorkItemId");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("SourceSystem", "SourceReference")
                        .IsUnique();

                    b.ToTable("insurance_work_items", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.OfficeSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessHoursSummary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ConfirmationLeadHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultReminderIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("EnableCollectionsBoard")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableManagerQueue")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableRecallBoard")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableTodayBoard")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableTomorrowPrepBoard")
                        .HasColumnType("boolean");

                    b.Property<int>("InsuranceVerificationLeadDays")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ManagerEscalationUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("NoShowFollowUpDelayHours")
                        .HasColumnType("integer");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OverdueEscalationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagerEscalationUserId");

                    b.ToTable("office_settings", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.RecurringTaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("EndDateLocal")
                        .HasColumnType("date");

                    b.Property<int?>("EscalateAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EscalateToUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastGeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PatientReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RecurrenceInterval")
                        .HasColumnType("integer");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReminderRepeatMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<DateOnly>("StartDateLocal")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("TimeOfDayLocal")
                        .HasColumnType("interval");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EscalateToUserId");

                    b.HasIndex("IsActive");

                    b.ToTable("recurring_task_definitions", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("task_history", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppointmentWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BalanceFollowUpWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ClaimedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EscalateAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EscalateToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EscalatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("GeneratedForDateLocal")
                        .HasColumnType("date");

                    b.Property<Guid?>("GeneratedFromRecurringTaskDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InsuranceWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PatientReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReminderRepeatMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<DateTime?>("SnoozeUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentWorkItemId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("BalanceFollowUpWorkItemId");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DueAtUtc");

                    b.HasIndex("EscalateToUserId");

                    b.HasIndex("InsuranceWorkItemId");

                    b.HasIndex("Status");

                    b.HasIndex("GeneratedFromRecurringTaskDefinitionId", "GeneratedForDateLocal")
                        .IsUnique();

                    b.ToTable("task_items", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.UserNotificationPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EnableSoundForUrgentReminders")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveAssignedTaskReminders")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveOverdueEscalationAlerts")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveRecurringTaskGenerationAlerts")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceiveUnassignedTaskReminders")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("user_notification_preferences", (string)null);
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "PerformedByUser")
                        .WithMany("AuditEntries")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.BalanceFollowUpWorkItem", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.AppointmentWorkItem", "AppointmentWorkItem")
                        .WithMany("BalanceFollowUpWorkItems")
                        .HasForeignKey("AppointmentWorkItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppointmentWorkItem");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.ContactLog", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.AppointmentWorkItem", "AppointmentWorkItem")
                        .WithMany("ContactLogs")
                        .HasForeignKey("AppointmentWorkItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.BalanceFollowUpWorkItem", "BalanceFollowUpWorkItem")
                        .WithMany("ContactLogs")
                        .HasForeignKey("BalanceFollowUpWorkItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.InsuranceWorkItem", "InsuranceWorkItem")
                        .WithMany("ContactLogs")
                        .HasForeignKey("InsuranceWorkItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "PerformedByUser")
                        .WithMany("ContactLogs")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("ContactLogs")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AppointmentWorkItem");

                    b.Navigation("BalanceFollowUpWorkItem");

                    b.Navigation("InsuranceWorkItem");

                    b.Navigation("PerformedByUser");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.ExternalIntegrationRun", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.ExternalIntegrationProviderConfig", "ProviderConfig")
                        .WithMany("Runs")
                        .HasForeignKey("ProviderConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderConfig");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.InsuranceWorkItem", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.AppointmentWorkItem", "AppointmentWorkItem")
                        .WithMany("InsuranceWorkItems")
                        .HasForeignKey("AppointmentWorkItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "VerifiedByUser")
                        .WithMany("VerifiedInsuranceItems")
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppointmentWorkItem");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.OfficeSettings", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "ManagerEscalationUser")
                        .WithMany("EscalationSettings")
                        .HasForeignKey("ManagerEscalationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ManagerEscalationUser");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.RecurringTaskDefinition", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "AssignedUser")
                        .WithMany("AssignedRecurringTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedRecurringTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "EscalateToUser")
                        .WithMany("EscalatedRecurringTasks")
                        .HasForeignKey("EscalateToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("EscalateToUser");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskHistory", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "PerformedByUser")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.TaskItem", "TaskItem")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.AppointmentWorkItem", "AppointmentWorkItem")
                        .WithMany("Tasks")
                        .HasForeignKey("AppointmentWorkItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.BalanceFollowUpWorkItem", "BalanceFollowUpWorkItem")
                        .WithMany("Tasks")
                        .HasForeignKey("BalanceFollowUpWorkItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "ClaimedByUser")
                        .WithMany("ClaimedTasks")
                        .HasForeignKey("ClaimedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "EscalateToUser")
                        .WithMany("EscalatedTasks")
                        .HasForeignKey("EscalateToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.RecurringTaskDefinition", "GeneratedFromRecurringTaskDefinition")
                        .WithMany("GeneratedTasks")
                        .HasForeignKey("GeneratedFromRecurringTaskDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Task_Reminder.Api.Domain.Entities.InsuranceWorkItem", "InsuranceWorkItem")
                        .WithMany("Tasks")
                        .HasForeignKey("InsuranceWorkItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppointmentWorkItem");

                    b.Navigation("AssignedUser");

                    b.Navigation("BalanceFollowUpWorkItem");

                    b.Navigation("ClaimedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("EscalateToUser");

                    b.Navigation("GeneratedFromRecurringTaskDefinition");

                    b.Navigation("InsuranceWorkItem");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.UserNotificationPreference", b =>
                {
                    b.HasOne("Task_Reminder.Api.Domain.Entities.User", "User")
                        .WithOne("NotificationPreference")
                        .HasForeignKey("Task_Reminder.Api.Domain.Entities.UserNotificationPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.AppointmentWorkItem", b =>
                {
                    b.Navigation("BalanceFollowUpWorkItems");

                    b.Navigation("ContactLogs");

                    b.Navigation("InsuranceWorkItems");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.BalanceFollowUpWorkItem", b =>
                {
                    b.Navigation("ContactLogs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.ExternalIntegrationProviderConfig", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.InsuranceWorkItem", b =>
                {
                    b.Navigation("ContactLogs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.RecurringTaskDefinition", b =>
                {
                    b.Navigation("GeneratedTasks");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("ContactLogs");

                    b.Navigation("HistoryEntries");
                });

            modelBuilder.Entity("Task_Reminder.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedRecurringTasks");

                    b.Navigation("AssignedTasks");

                    b.Navigation("AuditEntries");

                    b.Navigation("ClaimedTasks");

                    b.Navigation("ContactLogs");

                    b.Navigation("CreatedRecurringTasks");

                    b.Navigation("CreatedTasks");

                    b.Navigation("EscalatedRecurringTasks");

                    b.Navigation("EscalatedTasks");

                    b.Navigation("EscalationSettings");

                    b.Navigation("HistoryEntries");

                    b.Navigation("NotificationPreference");

                    b.Navigation("VerifiedInsuranceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
